import Head from 'next/head'
import Image from 'next/image'
import { Button } from '../components/Button'
import style from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio with NextJs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={style.header}>

        <div className={style.copy}>
          <p>
            <span className={style.hello}>Hello</span>
            <span className={style.name}>I&apos;m DltFred</span>
            full stack developer
          </p>
          <Button type={'orange-outline'}>Here me</Button>
        </div>
        <Image src="/profile.png" alt="profile" height={200} width={200} />
      </header>
    </>
  )
}
